typography_spectrum: 0.2531273295171559
color:
  brandStrength: 0.8513861116953194
  lightness: 0.44012275827117264
  saturation: 0.4040679147001356
  rhythmicContrast: 0.191885327687487
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.8277512439526618
name: HELSEBANKEN
navigation:
  - url: 'http://www.helsebanken.net/'
    name: ...the other side...
    type: external
title: Velkommen til Helsebanken!
description: ...helse er ferskvare - invester i dag!
