typography_spectrum: 0.7156912502832711
color:
  brandStrength: 0.776034843409434
  lightness: 0.044737478252500296
  saturation: 0.5784090142697096
  rhythmicContrast: 0.5581420604139566
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
layout_spectrum: 0.04308118112385273
name: HELSEBANKEN
navigation:
  - url: 'http://www.helsebanken.net/'
    name: ...the other side...
    type: external
title: Velkommen til Helsebanken!
description: ...helse er ferskvare - invester i dag!
