typography_spectrum: 0.8925219045486301
color:
  brandStrength: 0.4205040915403515
  lightness: 0.8247915538959205
  saturation: 0.9590391092933714
  rhythmicContrast: 0.5405360595323145
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.19621751178056002
name: HELSEBANKEN
navigation:
  - url: 'http://www.helsebanken.net/'
    name: ...the other side...
    type: external
title: Velkommen til Helsebanken!
description: ...helse er ferskvare - invester i dag!
